### ISSUE TITLE
Socket.IO api should be able to handle requests to join and leave meeting rooms

### ISSUE THREAD

**Issue by davidvandusen** [OpenTree-Education/rhizone-lms#177]
## Expected behaviour

When Socket.IO on the api receives a `meeting:join` message with a meeting id as its data, if the current principal is a participant in that meeting, it adds the sending socket to the room `meeting:id` where `id` is the meeting id. After adding the socket to the room, it emits a `meeting:joined` message to the socket with the meeting id as its data.

When Socket.IO on the api receives a `meeting:leave` message with a meeting id as its data, it removes the sending socket from the room `meeting:id` where `id` is the meeting id. After removing the socket from the room, it emits a `meeting:left` message to the socket with the meeting id as its data.

## Actual behaviour

It's not possible for sockets to be in meeting rooms.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by BRashad** [comment]
As I can see from the meetingsService.js file `findMeeting` function checks `if the current principal is a participant in that meeting`. I will use it to fulfill the `if the current principal is a participant in that meeting` part of the ticket. 
Also on the client-side  `Socket.IO already receives a meeting: join message with a meeting id as its data`. Do I have to write separate logic to emit meeting: join message on the server-side too? or I can somehow use the existing client-side socket emitting results on the server-side?

**Comment by davidvandusen** [comment]
@BRashad In your comment you say:

> on the client-side Socket.IO already receives a meeting: join message with a meeting id as its data

This is not the case. The client does not have any event handlers for `meeting:join` events. In fact, the client will never handle such messages, because those messages are intended for the server. Later on, the client will handle `meeting:joined` and `meeting:left` messages, but that behaviour is not part of this issue.

To clarify, when a meeting is viewed in the webapp:

1. The client sends a `meeting:join` event to request to join a meeting.
2. The server receives the `meeting:join` event and, if the security checks pass, adds the socket to the meeting room and sends a `meeting:joined` back to the client.

Later on, when the user navigates away from viewing the meeting:

1. The client sends a `meeting:leave` event to the server to indicate it no longer wants to get updates for that meeting.
2. The server receives the `meeting:leave` event, removes the socket from the meeting room, and sends a `meeting:left` message back to the client.

Number 1 in both of those lists is already done. This ticket is to do number 2 in those lists.

**Comment by BRashad** [comment]
Now I see. Thank you @davidvandusen for clarification.
