### ISSUE TITLE
The meeting page should add newly added meeting notes in response to WebSocket messages

### ISSUE THREAD

**Issue by davidvandusen** [OpenTree-Education/rhizone-lms#179]
## Expected behaviour

On the meeting route/page in the webapp, after connecting to the WebSocket and having successfully joined the meeting room, when receiving a `meeting_note:created` message, the note received in the payload of the message is added into list of notes in the appropriate position.

## Actual behaviour

When a `meeting_note:created` message is received, the UI doesn't make any updates.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by eileenxue** [comment]
@davidvandusen I'm trying to clarify if the actual behaviour mentioned in this ticket exists in the application. I can't find any mentions of `meeting_note:added` in the source code.

**Comment by davidvandusen** [comment]
@eileenxue It doesn't exist in the application. It will be added in the ticket #175, though it looks like it uses `created` instead of `added`, so that might be a typo. Those tickets can be done in any order. Feel free to to the other ticket first if you think it makes sense to.

**Comment by eileenxue** [comment]
@davidvandusen Thanks David, let me take a look at that ticket as well. Should we use `created` or `added` then?

**Comment by eileenxue** [comment]
@davidvandusen I decided to tend to #175 first, it seems like it'll make more sense for me. Plus it deals with the backend whereas this deal with the frontend and the meeting page is still under development in another PR. Trying to avoid conflicts.

I will use the term `created` as mentioned in the other ticket unless you think otherwise.

**Comment by BRashad** [comment]
To clarify. In this part of the ticket, `the note received in the payload of the message is added into the list of notes in the appropriate position` all it requires is to get the content/payload of the message, related to the note and render it in UI?

**Comment by davidvandusen** [comment]
@BRashad The rendering of the notes is already handled in the same component that manages the data, so nothing will need to be passed anywhere.

In this ticket, the note from the `meeting_note:created` event needs to be added into the already existing list of notes that were fetched using `useApiData`. That may require managing the api data as local state, since the `useApiData` hook does not expose a way to modify the state.

**Comment by BRashad** [comment]
Thanks for the clarification.
