### ISSUE TITLE
Meeting page does not re-render with new state after clicking on another meeting title in the meeting drawer

### ISSUE THREAD

**Issue by tungtung233** [OpenTree-Education/rhizone-lms#219]
## Expected behaviour

When navigating from one meeting page to another, via the meeting drawer, the state should automatically update and the page should re-render.

## Actual behaviour

When navigating from `/` to a meeting page via the meeting drawer, the page re-renders with the proper state. However, when navigating from one meeting page to another meeting page, via the meeting drawer, the state does not get updated, so the page does not update. State only gets updated after refreshing the page. 

## Steps to reproduce

Open the meeting drawer, click on a meeting. Then click on another meeting. The state doesn't change :( 

## Details and resources

![Peek 2021-12-17 15-13](https://user-images.githubusercontent.com/80285812/146606438-b0a7d260-2912-4997-8bea-a67003e9c934.gif)

Clicking on the Dec 25th, 8am meeting link brings you to `/meetings/15`. From that page, clicking on the Dec 1st, 10am meeting link brings you to `/meetings/12`, but the information on the page doesn't actually change

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by davidvandusen** [comment]
This may have been addressed during work on #129 or #254. It doesn't appear to be an issue in dev, and there is no prod data to test it on. Closing this issue until it comes up again.
