### ISSUE TITLE
Competencies cannot be added to the database from the webapp

### ISSUE THREAD

**Issue by davidvandusen** [OpenTree-Education/rhizone-lms#275]
## Expected behaviour

A form in the webapp creates a new competency and links it to the current user's competency model.

## Actual behaviour

Competencies need to be added directly to the database or by hitting the API directly.

## Details and resources

The form could appear on the `/competencies` page. It should have separate text fields for entering the title and description of the competency.

The user experience could be improved by clearing out the form after it submits successfully to allow for another competency to be easily added.

The list of all competencies should be updated after successfully inserting the new one.

Success and error messages are presented depending on the outcome of the request.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by BRashad** [comment]
I have only one question: Have you tested simulated the server-side error in case the user competency input can not be successfully inserted into DB ?

**Comment by BRashad** [comment]
on my local machine, all work as per the ticket requirements. Subject to question feedback on server-side error upon unsuccessful competency insert into DB. the case is good to be merged. 

![Screen Shot 2022-02-08 at 2 29 12 PM](https://user-images.githubusercontent.com/10593476/153078854-a715a6ea-05fd-4d15-b07b-73b12c0ff98f.png)
![Screen Shot 2022-02-08 at 2 29 26 PM](https://user-images.githubusercontent.com/10593476/153078860-ff931589-355f-49be-88e3-1c6d33884036.png)
