### ISSUE TITLE
Dependabot advisories are unaddressed

### ISSUE THREAD

**Issue by davidvandusen** [OpenTree-Education/rhizone-lms#298]
## Expected behaviour

The advisories in dependabot are addressed.

## Actual behaviour

We got a batch of dependabot advisories. https://github.com/OpenTree-Education/rhizone-lms/security/dependabot

## Details and resources

Upgrading to react-scripts@5.0 might address a handful of gnarly ones. There's an issue, #259, to take a look at that.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by BRashad** [comment]
this link takes me to the non-existing page error: 404https://github.com/OpenTree-Education/rhizone-lms/security/dependabot

**Comment by davidvandusen** [comment]
@BRashad I guess users with collaborator access can't see the security tab. In that case, this ticket will have to be done by or in collaboration with someone with admin access.

**Comment by BRashad** [comment]
> @BRashad I guess users with collaborator access can't see the security tab. In that case, this ticket will have to be done by or in collaboration with someone with admin access.

ok. who has admin access? should i continue attempting to review this PR?

**Comment by BRashad** [comment]
Need clarification: does it mean as a priority we need to focus on Breaking Changes as per the screenshot? or you ask for a specific breaking change for the so-called  Dependabot?
![Screen Shot 2022-02-08 at 2 43 27 PM](https://user-images.githubusercontent.com/10593476/153081366-c21aefa8-f316-4c5c-a785-2260260cc3de.png)

**Comment by davidvandusen** [comment]
@BRashad Wait, I thought you weren't able to see the dependabot advisories. If you can't access the link you mentioned earlier, then how did you take that screen shot?

**Comment by BRashad** [comment]
yes that link does not work. but i followed #259 and took me there. I did not think that's this is same link. 
![Screen Shot 2022-02-08 at 2 51 17 PM](https://user-images.githubusercontent.com/10593476/153081711-c7ad60b5-a695-4089-9ec5-9b91f91b7c05.png)
d

**Comment by davidvandusen** [comment]
@BRashad Ok, so your question is actually about a different issue, not this one. This issue is strictly about the dependabot advisories, which you don't have access to, so don't worry about this one until it gets pulled into a sprint.

If you have questions about the other issue, feel free to leave them there so that whoever picks up that issue benefits from reading the answers to your questions.

**Comment by BRashad** [comment]
no more questions.

**Comment by davidvandusen** [comment]
Addressed during #259.
