### ISSUE TITLE
User view needs a profile button to get to profile view

### ISSUE THREAD

**Issue by glenyingchua** [OpenTree-Education/rhizone-lms#345]
## Expected behaviour

A profile button is located on the top right beside meeting notes and sign out. When user hovers on profile button, profile word is shown beneath. When user clicks on profile button, user redirects to profile page.

A route to user profiles will need to be created.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by denizedaza** [comment]
Issue resolved with pull request #351
