### ISSUE TITLE
Profile page needs profile picture, name, description with links

### ISSUE THREAD

**Issue by glenyingchua** [OpenTree-Education/rhizone-lms#346]
## Expected behaviour

When user lands on profile page, they should see their profile picture (circular with blue border) beside their name, bolded large, with email and social media links, and summary underneath. 

On mobile view, all information consolidates underneath profile picture. 

Github user table needs fields for added profile information. 

Some user information can be pulled from Github, but the other fields will be blank until edited by user.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by SiriusLL** [comment]
As a group we have decided to split this issue into an additional issue in order to resolve this roadblock because fetching data is not required by any other issues at the moment.

**Comment by Ayako-Yokoe** [comment]
We split the issue into #355 and #356, so we are going to close this issue.
