### ISSUE TITLE
Profile needs links to other LMS features

### ISSUE THREAD

**Issue by glenyingchua** [OpenTree-Education/rhizone-lms#348]
## Expected behaviour

User can see buttons to journal, competencies and progress underneath profile summary. User will be redirected to appropriate feature when they click on corresponding button.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by MahoMori** [comment]
I think we all agreed to show progress on the profile page, so our team decided not to implement a button to progress.

**Comment by sheacronin** [comment]
We have created the code for the button links, but are waiting on issue #346 to be completed before making a pull request because our code will need to be inserted into the Profile component that they build out.
