### ISSUE TITLE
Profile view should have progress trackers

### ISSUE THREAD

**Issue by glenyingchua** [OpenTree-Education/rhizone-lms#349]
## Expected behaviour

Users will see a progress view with two types of trackers. First, a circular rating to showcase competencies; second, a linear bar to showcase progression through a program. 

The circular rating will be dependent on the already existing competency table. The linear progress table will be hardcoded, but designed to fetch progress from a curriculum table.

Note: Out of scope - will depend on a curriculum or programs table with start and end dates.  

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by denizedaza** [comment]
> The linear progress table will be hardcoded, but designed to fetch progress from a curriculum table.

The curriculum table will be a new `Programs` table with the `start_date` and `end_date` fields added to the database

**Comment by denizedaza** [comment]
Until the #355 and #356 database issues are resolved, we will be using placeholders for the areas we would be connecting to the database in the progress tracker.

**Comment by denizedaza** [comment]
@seidior to track the linear progress with `start_date` and `end_date` and display the progress as a percentage, I was looking at a third party plugin (either dayjs: https://day.js.org/en/ or if there is something similar to it). Would this be something we can use? What is the best way to parse and calculate the dates? 

My thought process was: 
Ideally, we would use the plugin to subtract the `start_date` from the `end_date` (or vice versa, dates are tricky) as an integer variable (called `time_period` for example). 
Then, we would have another variable called `current_date` to grab the current date, subtract it from the `end_date` as another integer. 
**Then** calculate `current_date` over `time_period` to get the percentage.

**Comment by denizedaza** [comment]
> Until the #355 and #356 database issues are resolved, we will be using placeholders for the areas we would be connecting to the database in the progress tracker. Working on front-end aspects only.

Will split the database aspects of the trackers into a new ticket. Closing for front-end aspects resolved
