### ISSUE TITLE
Profile page should have a personalized greeting for the user

### ISSUE THREAD

**Issue by glenyingchua** [OpenTree-Education/rhizone-lms#350]
## Expected behaviour

The user will see a personalized greeting, depending on the time of day and user language, displayed above their name and profile picture.

Information can usually be grabbed from window.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by sheacronin** [comment]
We're looking into having custom greetings for the user based on their preferred language and were thinking about using a package for this. We found this as an example https://www.npmjs.com/package/translate, and were wondering if using something like this would be okay for the project?

**Comment by seidior** [comment]
> We found this as an example https://www.npmjs.com/package/translate, and were wondering if using something like this would be okay for the project?

This seems to use Google Translate on the backend, and I have some thoughts about this:

- I think it might be slightly overkill to add GT for just a greeting.
- Using a machine translate process might be a bit fraught. Let's take English for example. "Hi", "Hello", "Hey there", "Greetings", "Salutations", "Good morning", and others are all roughly equivalent greetings, but where I'd say "hi" to everyone in the cohort, I would say "Good morning, Mr. President" to POTUS. So we would have to choose a base greeting that would give the same sense of formality and familiarity across different languages; however, with a machine translation service, it will probably default to a more formal translation such as 様 in Japanese, which would be the wrong vibe.

I think the better option would be to create an object that stores greetings, and we can accept PRs to extend the greetings to new languages as people see fit. This is a totally fine thing to hard-code. Something along the lines of:

```typescript
type GreetingType = {
    greeting: string;
    delimiter: string;
    beginning_punct: string;
    ending_punct: string;
    ltr: "ltr" | "rtl";
}

let morning_greetings = new Map<string, GreetingType>();
morning_greetings.set("en", {
  beginning_punct: "",
  greeting: "Good morning",
  delimiter: ", ",
  ending_punct: "!",
  ltr: "ltr"});
morning_greetings.set("es", {
  beginning_punct: "¡",
  greeting: "Buenos días",
  delimiter: ", ",
  ending_punct: "!",
  ltr: "ltr"});
morning_greetings.set("ar", {
  beginning_punct: "",
  greeting: "صباح الخير",
  delimiter: " ",
  ending_punct: "!",
  ltr: "rtl"});

const user_greeting = morning_greetings.get(current_user.preferred_language) ||
                      morning_greetings.get("en")!;

const user_greeting_string = user_greeting.beginning_punct +
                             user_greeting.greeting +
                             user_greeting.delimiter +
                             current_user.name +
                             user_greeting.ending_punct;

console.log(user_greeting_string);
```

(Using [ISO 639-1 language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)) (fill in the blanks with other languages, other greetings, and whatnot)

I'd love to know what the rest of the team thinks about this, though.

**Comment by MahoMori** [comment]
We were thinking it would be cumbersome to hard-code it, but as you pointed out, it would be too much to add a package just for the greeting. I'm relieved you said it's fine to hard-code.

**Comment by seidior** [comment]
Like I said, we can always build out that feature more and more as time goes by and as more multilingual people contribute to the project, so don't worry about having every language right now. Just focus on the ones where you feel like you have a good sense of the language to use the right greeting, and ask the rest of the contributors who know about other languages to pitch in once you finish building out the feature.

I can pitch in for Spanish, if no one else knows it.

(Also you totally don't have to build out the feature as I showed in my code example above. That's just an example of how I'd imagine that I would build it, absent of the architecture of the project.)

**Comment by seidior** [comment]
Going forward, I'm curious as to what y'all have decided for personalized greetings. I'm guessing:

- Good morning
- Good afternoon
- Good evening
- the equivalent of the above, but in each supported language

The problem with time of day is:

- Do you get the time of day from the browser or from a selection made by the user and saved into the database?
- When does *evening* start, precisely? Everyone has different ideas!

(Not to say it shouldn't be done, but you'll want to work through the ambiguity before finishing the feature.)

What other greetings do you think we should have? What do you think our intended user would expect, and what do you think would bring them surprise and delight?

**Comment by glenyingchua** [comment]
My default suggestion would be to keep it simple. A package, like the one Shea identified, would be great for a more complex application of customized/able greetings or other functions as well. 

I'm thinking for now, as a base level, we could satisfy each mentee's language-of-choice for this iteration, so everyone feels included and represented, and we can continue to expand or use a new system in the future. 

I like the idea of 
- Good morning, [Name]
- Good afternoon, [Name]
- Good evening, [Name]

Re: Time of day. We might want to go with the more universally agreed-upon time frames of morning, afternoon, and evening, which I believe are: 

Morning     5 am to 12 pm (noon)
Afternoon  12 pm to 5 pm
Evening     5 pm to 9 pm
Night         9 pm to 4 am (If we want to add night)

Consensus on these details would be great to move forward!

**Comment by sheacronin** [comment]
I agree that hard-coding the language values is a good idea for the scope of this project! Right now, our code says:

- 1am-12pm = Good morning
- 12pm-5pm = Good afternoon
- 5pm-12am = Good evening

I agree we could adjust these values to make "Good evening" 5pm-4am and "Good morning" 5am-12pm instead. 

We also currently have the format of "{Hello in preferred language} {userName}! {timeBasedGreeting}." Maybe keeping this format and just having translations of only "hello" in different languages, and having the time-dependent greetings only in English could simplify what we need to do (as @achichikalova suggests). A potential problem I can think of is if there are any languages we want to support that might not have a generic greeting that doesn't depend on the time - I'm not sure if this would be an issue though.

**Comment by Nazanin-Rezaei** [comment]
We defined the preferred language as a hardcode for now and we set it as French. We create 3 arrays for the morning, afternoon, and evening greetings for different languages then we create a function that gets the greeting objects depending on the time and the user's preferred language and returns the greeting as a string.
