### ISSUE TITLE
Competencies table will need to be updated with a category_id

### ISSUE THREAD

**Issue by daveytech** [OpenTree-Education/rhizone-lms#370]
## Expected behaviour

Competencies table should be connected to categories through a category_id so competencies can be grouped and organized for reflections

## Details and resources

ERD to be included.

Migration 16.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by denizedaza** [comment]
Yesterday: 
- re-pulled from `main` after reverts were applied. Migration numbers were changed so updated branch to match
- deleted previous version of the branch (before reverts) and pushed updated version of branch to repo to look over
- related to #369 so will wait for approved PR for that issue before pushing this forward
