### ISSUE TITLE
A route is needed to fetch all competencies grouped by category

### ISSUE THREAD

**Issue by daveytech** [OpenTree-Education/rhizone-lms#374]
## Expected behaviour

There should be a route available to return all competencies grouped by categories.

competencies/categories

This ticket is grouped with issues #372 , #373 

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by sheacronin** [comment]
This issue has been updated to reflect that we want to return all competencies grouped by category, but are no longer doing this by the author id and are just returning all categories with their competencies from the database
