### ISSUE TITLE
There should be a route that renders the list of reflections based on category ids

### ISSUE THREAD

**Issue by daveytech** [OpenTree-Education/rhizone-lms#375]
## Expected behaviour

The route **/questionnaires/categories** will render the list of questionnaires based on category ids.

This can be found by navigating through **/reflections/competencies**.

This ticket is grouped with issues #372 - #374 .

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by Ayako-Yokoe** [comment]
There seems to be a name conflict in a router/path.
We already have a route **/questionnaires/:id**, and we're going to add **/questionnaires/categories**.

_questionnairesRouter.tsx_
(existing)
**questionnairesRouter.get('/:id', async (req, res, next) => { ... }**
(newly added)
**questionnairesRouter.get('/categories', async (req, res, next) => {...}**

We need to keep **/questionnaires/:id** when we retrieve the questionnaire with the questionnaire id to show on questionnaire pages.

_Questionnaire.tsx_
path:  `/questionnaires/${questionnaireId}`,

So, I would suggest we change the path name.

suggestion
_Questionnaire.tsx_
path: /questionnaires/**something**/${questionnaireId},

_questionnairesRouter.tsx_
questionnairesRouter.get('/**something**/:id', async (req, res, next) => {...}
