### ISSUE TITLE
Variables should be in camel case

### ISSUE THREAD

**Issue by Nazanin-Rezaei** [OpenTree-Education/rhizone-lms#396]
## Expected behaviour

Variables should be in camel case

## Actual behaviour

Not all variables are in camelCase format.
![image](https://user-images.githubusercontent.com/73320246/175367064-a0f8fef5-efab-42a3-bd89-a69458826573.png)
![image](https://user-images.githubusercontent.com/73320246/175367199-fa79800f-1936-4352-966c-55a2f9779fa7.png)

## Details and resources

This issue is based on the #393 issue which linter check the camel casing format of the variables

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by achichikalova** [comment]
Missed one variable from MeetingQuickView.tsx file.
