### ISSUE TITLE
There should be a categories_questionnaires table 

### ISSUE THREAD

**Issue by daveytech** [OpenTree-Education/rhizone-lms#404]
## Expected behaviour

There should be a table that joins categories and questionnaires to fetch questionnaires more effectively.

## Actual behaviour

No join table exists at this moment.

## Details and resources

Should look similar to this 

`create table categories_questionnaires (
  id bigserial primary key,
  category_id bigint references categories(id),
  questionnaire_id bigint references questionnaires(id)
);`

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by sheacronin** [comment]
I have a question about the code for the migration file. The suggested code is:
```sql
CREATE TABLE categories_questionnaires (
    id bigserial primary key, 
    category_id bigint references categories(id),
    questionnaire_id bigint references questionnaires(id) 
);
```

But our other tables are formatted more closely to something like:
```sql
CREATE TABLE categories_questionnaires (
  id BIGINT NOT NULL AUTO_INCREMENT, 
  category_id BIGINT NOT NULL,
  questionnaire_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  INDEX categories_questionnaires_category_id (category_id),
  FOREIGN KEY (category_id) REFERENCES categories(id),
  INDEX categories_questionnaires_questionnaire_id (questionnaire_id),
  FOREIGN KEY (questionnaires_id) REFERENCES questionnaires(id)
);
```

Is there one way that would be better for this issue, or a combination of the two formats?

**Comment by daveytech** [comment]
@sheacronin Let's stay inline with the previous way of forming the tables. Your version is great!
