### ISSUE TITLE
There should be a migration file that initializes the database structure for programs

### ISSUE THREAD

**Issue by daveytech** [OpenTree-Education/rhizone-lms#412]
## Expected behaviour

Database should have tables that represent the program structure including programs, curriculums, activities, activity_types and participant_activities. 

## Details and resources

**curriculums**
- id
- title
- principal_id (FK)

**programs**
- id
- title
- start_date
- end_date
- curriculum_id (FK)
- principal_id (FK)

**activity_types**
- id
- title

**activities**
- id
- title
- description_text
- curriculum_week (one integer)
- curriculum_day (one integer)
- start_time (optional - minutes from midnight)
- end_time (optional - minutes from midnight)
- duration (optional - minutes)
- activity_type_id (FK)
- curriculum_id (FK)

**participant_activities**
- id
- program_id (FK)
- activity_id (FK)
- principal_id (FK)
- completed (boolean)

Link to ERD - https://excalidraw.com/#room=6e846bdae45f1ba686a1,I9zniI4UTiDSHQ7qv7iCyw

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by seidior** [comment]
Developers assigned to this ticket should also define some example activity types and insert them into the activity_types table at the end of the migration after the activity_types table is created.
