### ISSUE TITLE
Clicking an event in the calendar should show a popup dialog with more information

### ISSUE THREAD

**Issue by seidior** [OpenTree-Education/rhizone-lms#433]
## Description

With the merger of issue #428, we will have a calendar display of all program activities for the user. However, the activities are not clickable to find out more information such as time range, description, etc.

The expectation is that an MUI Dialog will pop up showing the details of the activity. Clicking a close button or clicking in the shaded area outside of the Dialog will close the dialog. Clicking another activity will show the Dialog but with the details of that activity instead.

## Details and resources

You will need to use the Dialog component from MUI, and you will need to use React state management in order to handle the change of contents of the Dialog and whether or not it's open.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by seidior** [comment]
It's generally not advisable, because we want to keep each team's work isolated into each branch before merger in case we need to roll back or delete changes, but to keep things moving along, I've created a branch for this issue and incorporated the latest from #428 so that we can start work on this. But please be advised, any work on #428 may end up disrupting code you're working on here, so try to work on the parts of this (React state management and incorporating the MUI Dialog component, for example) that aren't tied strongly to the calendar, and leave the parts tying the dialog with the calendar until the end; hopefully PR #435 will be merged by then.

**Comment by seidior** [comment]
Here's the latest status of this ticket:

- @ChainShoe-Z and @phoebehala got the MUI Dialog to display when clicking on an event. They came up with a great solution that works to show a dialog even if you change the program to a different program and then click an event.
- After all the major changes in #428, I had to adapt the code that was here to bring it up to date and preserve that working functionality as much as possible.

Here's what still needs to be done:

- I feel like the click handling could be done a little better instead of overloading one function with handling both open and close functionality.
- The dialog is only being passed the title of the event. It needs to be passed all the details we want to show in the dialog.
- The dialog needs much better styling, which will address the `// TODO` comment in `ActivityDialog.tsx`.

If you've previously worked on this ticket, you'll need to:
```shell
git pull
docker compose down
docker compose build
docker compose up
cd webapp
yarn develop
```
before working on this again because there were changes merged in from main that affect database migrations as well.

**Comment by daveytech** [comment]
EOD Update:

Progress was made on rendering the data from event in the modal. Might have to be revised based on a possible redesign of the Program component. Further styling will be discussed and worked on.

After merging in the previous pull request, the use of a class component for Program is being reconsidered. If possible staying consistent with functional component solutions should be a priority. A decision on how to move forward on this ticket and the previous pull request #428 will happen tomorrow (Friday) morning.

**Comment by seidior** [comment]
Update: we're now taking a React function-component-based approach to bringing the disparate components together. `CalendarPage.tsx` is now `ProgramsPage.tsx`, and `Program.tsx` has now been removed.
