### ISSUE TITLE
The calendar page needs a more explicit way to go back to the home page

### ISSUE THREAD

**Issue by camianderson** [OpenTree-Education/rhizone-lms#446]
## Expected behaviour

Another option for the User to click and be rerouted to the home page. 

## Actual behaviour

Right now the only option that the user has is to click in the title of the App.

## Steps to reproduce

- Create a design proposition to the issue
- Get approval with the Team
- Implement the design

## Details and resources

We can try to implement a back button using an HTML button, or anchor link or an image that will redirect to the main page.
Here are some resources about it:
- https://uxdesign.cc/design-with-the-web-in-mind-d9f9df2e8812
- https://designshack.net/articles/trends/website-button-design/
- https://www.smashingmagazine.com/2022/08/back-button-ux-design/

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by camianderson** [comment]
I proposed to implement a "Back" home button in the top or in the bottom of the Calendar page as shown in the screen shots, but since this "Back" button behavior does not appears anywhere else in the application, we decided to don't add a new navigation element to the page.

![Screen Shot 2022-11-29 at 3 43 20 PM](https://user-images.githubusercontent.com/98124157/204647443-14c3caa4-b94a-4f8e-a086-97a57ce0d993.png)
![Screen Shot 2022-11-29 at 3 36 26 PM](https://user-images.githubusercontent.com/98124157/204647452-2a7a157e-3a73-46d0-b808-0974d3e61265.png)

**Comment by camianderson** [comment]
11/29 progress update: I was able to Implement a new home icon in the Navbar so the user can go back home at any time.
I am working in figure out how to style the hovering in the title so we can indicate to the user that they can click in the title to go back to the home page.

**Comment by camianderson** [comment]
11/30 progress update: I was able to add styling to the logo when it is hovered using Styled Components.

**Comment by SanazDn** [comment]
Great job! I approved.
