### ISSUE TITLE
Hover over the activities in the calendar shows a text cursor

### ISSUE THREAD

**Issue by Prabhj33t** [OpenTree-Education/rhizone-lms#449]
## Expected behaviour

Hovering over the activities in the agenda view changes the mouse cursor to a hand pointer instead of text cursor.

## Actual behaviour

Currently, we see a text cursor over the activities in the agenda view

## Steps to reproduce

Have to investigate the styling effect which we are using 
## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by Prabhj33t** [comment]
Update 
Changed the cursor behavior by adding a style component in the CSS file. 
Awaiting approval from Development Engineers to make a PR for this issue.

**Comment by seidior** [comment]
Prabh, I'm not seeing any code in your branch here in GitHub. Can you please run a `yarn delint` and push your branch from your local development environment to the branch on GitHub so we can see your work?
