### ISSUE TITLE
Add UI responsiveness to the main title, the program picker, the calendar and pop-up in the Program page

### ISSUE THREAD

**Issue by veranika-karpava** [OpenTree-Education/rhizone-lms#452]
## Expected behaviour

The main title and the ProgramPicker should be placed on separate horizontal lines on a small screen size.
The main title should be right-aligned on a small screen size.
The calendar should have day view on a small screen size.
The time in the ActivityDialog should be placed on separate line on a small screen size.

## Actual behaviour

The main title and the ProgramPicker is placed in one line. It looks good on tablet and desktop screens, but needs re-flow on a small screen.
The calendar looks the same on all screen sizes.
The time of activity in the ProgramActivityDialog needs re-flow on small screen size.

## Details and resources

Mobile breakpoint (min-width: 360px)
* The title of the page should be on a separate horizontal line.
* The Program Picker should be on a separate horizontal line after title of the page
* The width of the Program Picker's input should be less than screen size.
* The font-size of the Program Pickers should be smaller than for the desktop screen.
* The calendar should display only day view of the calendar. 
* Buttons of the month/week/agenda shouldn't be displayed.
* The time of the activity in ProgramActivityDialog should be displayed on a separate horizontal line. 

![Screenshot 2022-11-28 at 15 17 10](https://user-images.githubusercontent.com/92657405/204400900-a31591ef-2365-4f4c-bb76-b1785187b72c.png)

![Screenshot 2022-11-28 at 15 25 29](https://user-images.githubusercontent.com/92657405/204402068-7d084a32-2483-45f7-97b0-5d154f57eb6e.png)

Tablet breakpoint (min-width: 768px) and Desktop breakpoint (min-width: 1440px)
*UI looks good. 

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by seidior** [comment]
Brought this branch up to date with `main` and ran `yarn delint`. Great work so far, Veranika!

**Comment by veranika-karpava** [comment]
Update 12/5: 
* create currentWidth state for getting current width of the screen and also update this state every time when the screen size is changed
* update default current view depends on the current width of the screen
*  create views state for displaying types of the calendar on different screen sizes and update views state when the screen size is changed
*  add styling for event in day view calendar
* still working on agenda styling

![Screenshot 2022-12-05 at 20 33 40](https://user-images.githubusercontent.com/92657405/205815921-25a40d97-3d85-4c4e-83f4-f42bd1993a7d.png)

![Screenshot 2022-12-05 at 20 34 13](https://user-images.githubusercontent.com/92657405/205815942-22896993-b074-49d2-8068-a00abca9daf3.png)
