### ISSUE TITLE
programsRouter should support retrieval and updating of ParticipantActivities completion status

### ISSUE THREAD

**Issue by rrabinovitch** [OpenTree-Education/rhizone-lms#455]
## Expected behaviour

There should be two programs router functions that return a participant activity's `completed` status and allow for the value of that attribute to be modified.

## Details and resources

This ticket is associated with #454 and #457 in order to fulfill the product spec requirement for a [user to be able to mark an activity as complete](https://docs.google.com/document/d/1bYpceHQJZmm8h4opFTvTvZua1Xn39E1ZfNYDiDds7PM/edit#heading=h.q7slb8flu34l).

The two `programsRouter` functions should be something along the lines of:
- `programsRouter.get('/activityStatus/:programId/:activityId')` - returns the `completed` status of a given `participantActivity`. this function will allow a user to get their own status (admin access to be addressed later on)
- `programsRouter.post('/activityStatus/:programId/:activityId')` - modifies the `completed` value of an existing `participantActivity` (`POST` instead of `PUT` since we're creating new records instead of updating them)
  - in the POST body, there should be info about what the `completed` value is being changed to (eg, `{"completed": true}`)
  - ~~associated service function should only allow activities of `type: assignment` to have this attribute updated~~

The functions should take the following parameters: `principal_id` (corresponding to the user whose activity status is being tracked), `program_id`, and `activity_id`

`__tests__/programsRouter.ts` should also be updated to test these new router functions.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by rrabinovitch** [comment]
Questions to discuss:
- [ ] are ParticipantActivities records created automatically for each user, or should updating the completion status create a new record, or something other flow?
- [ ] does it matter whether this issue gets addressed before or after #454?

**Comment by rrabinovitch** [comment]
11/29 progress update: pseudocoded to plan code changes. will catch up on latest discussion in C4 channel tomorrow in order to further flesh out pseudocode and start translating it into code changes.

**Comment by rrabinovitch** [comment]
11/30 progress update: built out the getter function. tomorrow will continue with adding in necessary checks/error handling and following up with setter function

**Comment by rrabinovitch** [comment]
> ~~associated service function should only allow activities of type: assignment to have this attribute updated~~

per 12/1 discussion w Davey, this check should only be taken care of on the webapp side (see #428)

**Comment by rrabinovitch** [comment]
12/2 progress update:
- started outlining and building out tests for both functions
- waiting for response from team to request for eyes on setter function code to make sure I'm accessing/using request body `completed` value the right way
- waiting for response to questions about return statement in service setter function to eliminate "void" type error in router function

**Comment by seidior** [comment]
Hi there! I've merged in the latest changes from main to bring this branch up to date, and I tried to answer as many questions as I could. I love the communication and coordination with the other tickets, and you've got a strong start so far!

I've also added a stub for the route to get a list of all program activities and their completed statuses, which should help with the feature y'all were proposing at the end of last week.

Sorry about any confusion in the miscommunication about which functions would be throwing errors versus returning differently-shaped values.

**Comment by seidior** [comment]
As per our discussion this morning, I've removed the stubs I added before to restrict scope for the backend tickets. Valuable feedback, thanks!

**Comment by rrabinovitch** [comment]
12/6 progress update:
- addressed questions about service function return values with Davey - see comment [here](https://github.com/OpenTree-Education/rhizone-lms/issues/454#issuecomment-1340049056). this informed our decision to keep L54 as is - `!activityCompletionStatus` - because the variable's value is a hash, not a boolean
- built out setter function test
- waiting on a PR for #454 tomorrow in order to finalize this ticket as well

**Comment by rrabinovitch** [comment]
12/7 progress update:
- updated router functions and tests to reflect today's updates in service file
