### ISSUE TITLE
The ability to mark a task as completed from the frontend needs to be developed

### ISSUE THREAD

**Issue by seidior** [OpenTree-Education/rhizone-lms#457]
## Expected behavior

The last remaining big feature of the programs/activities component is the ability to mark activities (classified as "assignments") as completed and to have a visual indicator of which ones have been completed.

## Actual behavior

Right now in our Dialog component, it shows all of the details of the activity except its completion status, and there is no way to mark a task as completed.

## Details and resources

Minimum requirements for resolving this issue:

- When you click on a task and the Dialog element is presented, if the event is of type "assignment", the webapp should show the user's completion status (maybe with a checkbox?) in the Dialog.
- Clicking either the "mark completed" button or clicking a checkbox will send an API request to mark the task as completed.
   - If it's implemented as a button, there should be a different button that will now show to mark the task as "not completed", in case marking it completed was in error.
   - If it's implemented as a checkbox, unchecking the checkbox should send an API request to mark the task as not completed.

Stretch goals: (not required, but nice to have)

- There should be a visual indicator in the calendar for which activities are assignments and are either complete or not complete
- The button/checkbox to mark a task as complete should have a visible status to it to show the different states of the API request (like spinning or other animation), and the "completion" state should only be shown if the API request succeeds
- If we're unable to mark a task as completed, then there should be a visible error message displayed to the user so that they can act on it.

Reach goals: (not in scope, but if they are included, that'd be rad!)

- There should be a view that shows us a list of the activities that are assignments, their due dates, and their completion status. Think kind of like a to-do list view.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by wendyyng** [comment]
Just an update, I tried to add the checkbox to the dialog.
![image](https://user-images.githubusercontent.com/71687298/204892206-8b326c17-520e-42ae-ab8b-31e13ee633f1.png)

**Comment by wendyyng** [comment]
Update: I modified the CalendarEvent type to include activityType. Now the activity dialog would show the checkbox if the activityType is 'assignment'.
![image](https://user-images.githubusercontent.com/71687298/204901519-16e6cf89-146d-4303-a7c6-ed49e43d40e5.png)
![image](https://user-images.githubusercontent.com/71687298/204901560-8a19fd96-d788-484d-ab90-280dd14c4cb4.png)

**Comment by wendyyng** [comment]
Update:
I tried to create an updateApiData file since useApiData can only handle get request and other parts of the app also don't allow updating the existing data. I looked at Ruthie's issue #455 and include the activityStatus, programId and activityId in the path for the PATCH request:
```
fetch(`${process.env.REACT_APP_API_ORIGIN}${path}/${programId}/${activityId}`, {
        method: 'PATCH',
        credentials: sendCredentials ? 'include' : 'omit',
        signal,
      })
```

**Comment by wendyyng** [comment]
I referred to the CreateOrUpdateCompetencyForm to add the PATCH request to the ProgramActivityDialog. We can either use a button or checkbox, and to me buttons are a little bit easier to work with, since it'd be similar to like and unlike buttons. 

But I'll see if we can continue to use checkbox. I think it probably needs to use 'onChange'.

**Comment by wendyyng** [comment]
I changed the UI of the dialog based on the discussion today. But I think I'll wait #453 to be merged into main before making more commits so that the merge conflict won't be too complicated.
![image](https://user-images.githubusercontent.com/71687298/205396034-36af2a4d-1f34-4f69-b231-6785c6b8e6cb.png)
![image](https://user-images.githubusercontent.com/71687298/205396067-4375c7db-4218-4e08-8db0-c1c0cef654d9.png)

**Comment by wendyyng** [comment]
Instead of making another helper function, we can use MUI's text transformation to capitalize text.
```
        <DialogContentText id="alert-dialog-description" sx={{textTransform: 'capitalize'}}>
          <b>Activity Type:</b> {contents.activityType}
        </DialogContentText>
```

**Comment by wendyyng** [comment]
Added the buttons after merging from main:
![image](https://user-images.githubusercontent.com/71687298/205515829-57960973-d33e-4313-8275-8689cd46cb1a.png)
![image](https://user-images.githubusercontent.com/71687298/205515850-442ce59a-1bd6-42e7-a35b-a271bc72a328.png)

**Comment by wendyyng** [comment]
Adding radio button to the calendar:
![image](https://user-images.githubusercontent.com/71687298/205518652-2927c2f5-6e5b-4a27-999a-42aaf74fe0fa.png)
![image](https://user-images.githubusercontent.com/71687298/205518623-d2a27fc5-ff9a-4e14-b25c-ca40abca6eea.png)
```
 { event.event.activityType === decodeHTML('assignment') && (
          <RadioButtonUncheckedIcon fontSize='inherit' sx={{ pt: 0.5}}/>
        )
        }
```

**Comment by wendyyng** [comment]
Using different color for assignments:
![image](https://user-images.githubusercontent.com/71687298/205519727-5fc85201-4ca2-4ccb-ab85-a6eead34cfd6.png)
![image](https://user-images.githubusercontent.com/71687298/205519744-45e92638-7304-4b0c-b52d-cf8afb464e01.png)

**Comment by seidior** [comment]
I like it! Great work so far as always, @wendyyng.

Any particular reason the "Mark Complete"/"Mark Incomplete" button is better in the dialog content section rather than the left-side of the dialog actions section? No worries if you all discussed that already or if you think it's better there. I'm just curious as to the choice, that's all.

If you prefer the dialog content section, maybe we can move it to a table row like the rest of the content?

Also, it appears from your last update that adding the icon into the activity in week view is pushing over the width of the days in the all-day events section, so by the time Saturday hits, the all day section is pretty misaligned with the section below it. Not sure if that's just a WIP fragment or an uncaught error.

Heads up also, you should be getting a route to make your life easier so you can retrieve the statuses of all assignments at once instead of one by one. And I cleaned up some of my repeated styled-components values; sorry for leaving that kind of messy.

Two small other notes:
- again, let's make sure that we use `<strong>` instead of `<b>` to embolden text with emphasis, as seen in [this comment from 3 days ago](https://github.com/OpenTree-Education/rhizone-lms/issues/457#issuecomment-1335886369)
- you don't need to `decodeHTML()` for any values that can't be input by the user or don't have special characters. So, we'd want it on the description for sure, but we don't need to do it for an activity type, since those are hard-coded in the database and shouldn't have any special chars.

**Comment by wendyyng** [comment]
> I like it! Great work so far as always, @wendyyng.
> 
> Any particular reason the "Mark Complete"/"Mark Incomplete" button is better in the dialog content section rather than the left-side of the dialog actions section? No worries if you all discussed that already or if you think it's better there. I'm just curious as to the choice, that's all.
> 
> If you prefer the dialog content section, maybe we can move it to a table row like the rest of the content?
> 
> Also, it appears from your last update that adding the icon into the activity in week view is pushing over the width of the days in the all-day events section, so by the time Saturday hits, the all day section is pretty misaligned with the section below it. Not sure if that's just a WIP fragment or an uncaught error.
You're right! And based on the discussion today, this will be out of scope of this PR. So I won't make commits for this.
> 
> Heads up also, you should be getting a route to make your life easier so you can retrieve the statuses of all assignments at once instead of one by one. And I cleaned up some of my repeated styled-components values; sorry for leaving that kind of messy.
> 
> Two small other notes:
> 
> * again, let's make sure that we use `<strong>` instead of `<b>` to embolden text with emphasis, as seen in [this comment from 3 days ago](https://github.com/OpenTree-Education/rhizone-lms/issues/457#issuecomment-1335886369)
> * you don't need to `decodeHTML()` for any values that can't be input by the user or don't have special characters. So, we'd want it on the description for sure, but we don't need to do it for an activity type, since those are hard-coded in the database and shouldn't have any special chars.

**Comment by wendyyng** [comment]
Updates on the Dialog's UI:
Replacing the close button with the close icon on the top right:
![image](https://user-images.githubusercontent.com/71687298/205725461-ab106b8e-2f13-492a-b507-5fdd9fbf5345.png)

Moving the Mark Complete button to the left of the Dialog Section
![image](https://user-images.githubusercontent.com/71687298/205725998-7066b255-ca20-455f-a2f6-fd102b3940ea.png)

**Comment by wendyyng** [comment]
> I like it! Great work so far as always, @wendyyng.
> 
> Any particular reason the "Mark Complete"/"Mark Incomplete" button is better in the dialog content section rather than the left-side of the dialog actions section? No worries if you all discussed that already or if you think it's better there. I'm just curious as to the choice, that's all.
> 
> If you prefer the dialog content section, maybe we can move it to a table row like the rest of the content?
> 
> Also, it appears from your last update that adding the icon into the activity in week view is pushing over the width of the days in the all-day events section, so by the time Saturday hits, the all day section is pretty misaligned with the section below it. Not sure if that's just a WIP fragment or an uncaught error.
> 
> Heads up also, you should be getting a route to make your life easier so you can retrieve the statuses of all assignments at once instead of one by one. And I cleaned up some of my repeated styled-components values; sorry for leaving that kind of messy.
> 
> Two small other notes:
> 
> * again, let's make sure that we use `<strong>` instead of `<b>` to embolden text with emphasis, as seen in [this comment from 3 days ago](https://github.com/OpenTree-Education/rhizone-lms/issues/457#issuecomment-1335886369)
> * you don't need to `decodeHTML()` for any values that can't be input by the user or don't have special characters. So, we'd want it on the description for sure, but we don't need to do it for an activity type, since those are hard-coded in the database and shouldn't have any special chars.

**Adding the icon into the activity in week view is pushing over the width of the days in the all-day events section**
You're right! And based on the discussion today, this will be out of scope of this PR. So I won't make commits for this.

**Use <strong> instead of <b> to embolden text with emphasis**
Thanks for the reminder! For now we're using fontWeight: 'bold' instead though so no <strong> or <b> is being used.

**Don't need to decodeHTML() for any values that can't be input by the user or don't have special characters. So, we'd want it on the description for sure, but we don't need to do it for an activity type**
It has been removed! :)

**Comment by veranika-karpava** [comment]
Great work, Wendy. Both options look wonderful, but I prefer the first one.

**Comment by daveytech** [comment]
Thanks for working on those screenshots. I agree with the others, the first one is nice and clean! My vote is that one!

**Comment by wendyyng** [comment]
12/6: Working on the GET and POST for activity status
```
// Get Request for activity completsion status
  // programsRouter.get('/activityStatus/:programId/:activityId')
  const {
    data: activityCompletionStatus,
    error,
    isLoading,
  } = useApiData<ActivityCompletionStatus>({
    deps: [completed],
    path: `/programs/activityStatus/${contents.programId}/${contents.curriculumActivityId}`,
    sendCredentials: true,
  });
```
```
 // Post Request for updating activity completion status
  // programsRouter.post('/activityStatus/:programId/:activityId')
  // Using onClick for UI demo but onSubmit should be used in future development
  const onClick: FormEventHandler = event => {
    event.preventDefault();
    setCompleted(!completed);
    // fetch(
    //   `${process.env.REACT_APP_API_ORIGIN}/programs/activityStatus/${programId}/${activityId}`,
    //   {
    //     method: 'POST',
    //     credentials: 'include',
    //     headers: { 'Content-Type': 'application/json' },
    //   }
    // )
    //   .then(res => res.json())
    //   .then(({ data, error }) => {
    //     setCompleted(!completed);
    //     if (error) {
    //       setMarkCompletedError(error);
    //     }
    //     if (data) {
    //       setIsSuccessMessageVisible(true);
    //     }
    //   })
    //   .catch(error => {
    //     setCompleted(completed);
    //     setMarkCompletedError(error);
    //   });
  };
```

**Comment by wendyyng** [comment]
12/7 Continued to work on the GET & POST requests:
```
  const [completed, setCompleted] = useState(false);
  // const [markCompletedError, setMarkCompletedError] = useState(null);
  // const [isSuccessMessageVisible, setIsSuccessMessageVisible] = useState(false);

  // Get Request for activity completsion status
  // programsRouter.get('/activityStatus/:programId/:activityId')
  // return {activityId:1, participantActivityId: 1, completed: true}
  const {
    data: activityCompletionStatus,
    error,
    isLoading,
  } = useApiData<ActivityCompletionStatus>({
    deps: [completed],
    path: `/programs/activityStatus/${contents.programId}/${contents.curriculumActivityId}`,
    sendCredentials: true,
  });

  // Post Request for updating activity completion status
  // programsRouter.post('/activityStatus/:programId/:activityId')
  // request body shoud look like: {"completed": true}
  // Using onClick for UI demo but onSubmit should be used in future development
  const onClick: FormEventHandler = event => {
    event.preventDefault();
    setCompleted(!completed);
    // fetch(
    //   `${process.env.REACT_APP_API_ORIGIN}/programs/activityStatus/${contents.programId}/${contents.curriculumActivityId}`,
    //   {
    //     method: 'POST',
    //     credentials: 'include',
    //     headers: { 'Content-Type': 'application/json' },
    //     body: JSON.stringify({
    //     completed: !completed
    // }),
    //   },
    // )
    //   .then(res => res.json())
    //   .then(({ data, error }) => {
    //     setCompleted(!completed);
    //     if (error) {
    //       setMarkCompletedError(error);
    //     }
    //     if (data) {
    //       setIsSuccessMessageVisible(true);
    //     }
    //   })
    //   .catch(error => {
    //     setCompleted(completed);
    //     setMarkCompletedError(error);
    //   });
  };
```

**Comment by seidior** [comment]
Updates on the latest from this issue:

Phoebe and Wendy worked late into the night last night to make sure that this code was working given the changes to the backend code. We worked through some of the issues with React state management to be able to demonstrate working functionality, but the code isn't conformant to guidelines at the moment.

Next for this ticket:

- I'd love to find a way to useApiData instead of the `fetch()` call for the getter. The problem right now is that the getter needs to be called conditionally, which useApiData doesn't currently support.
- I'd love to move the PUT `fetch()` logic somewhere else like a helper function so that other code can use it, then add appropriate tests for that.
- There's currently minimal to no error handling if the getter or setter fail for any reason, so I'd love to see some code to handle that.
- Extraneous code comments need to be cleaned up and some refactoring needs to be done to get code to conform to guidelines
