### ISSUE TITLE
programsRouter GET programs function should implement error handling

### ISSUE THREAD

**Issue by rrabinovitch** [OpenTree-Education/rhizone-lms#464]
## Expected behaviour

The `programsRouter.get('/')` function should handle errors, as is done in other router functions in the code base.

## Actual behaviour

The function currently has no error handling.

## Details and resources

Wrap the service function call on L9 in programsRouter in a try/catch statement.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by wendyyng** [comment]
I wrapped the function in the try/catch statement. I think this would suffice?
```
programsRouter.get('/', async (req, res, next) => {
  let programsWithActivities;
  try {
      programsWithActivities = await listProgramsWithActivities();
  } catch (err) {
    next(err);
    return;
  }
  res.json(
    collectionEnvelope(programsWithActivities, programsWithActivities.length)
  );
});
```
