### ISSUE TITLE
The frontend should be adapted to use an API call that gets all assignments and their completion

### ISSUE THREAD

**Issue by seidior** [OpenTree-Education/rhizone-lms#470]
## Details and resources

As per issue #469, there will be an API route that will allow us to get the completed status of all assignments in a program at once. Right now in the webapp, we are retrieving this information one-by-one as needed.

In this issue, we will compile all work required to adapt the webapp to this new route for fetching the information. (The existing logic to set a new value for a completed status for an assignment should be otherwise unchanged, although if any changes to where we are storing assignments' completed statuses is required, then the setting logic may have to be updated for the state to persist.)

This issue is open for anyone who wants to tackle it.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by phoebehala** [comment]
Dec 12 progress update:
- Manually added rows to participant_activities table and tested #469 http://api.rhi.zone-development/programs/activityStatus/1
-  Tried to apply above route to the front end:
Fetch participantActivitiesCompletionList and push completion status to each of program.activities"

**Comment by phoebehala** [comment]
Dec 13 progress update:
- It now can pass the activities with completion status to the 'event' property of calendar
