### ISSUE TITLE
Change the colour of all day activity in month/week/day/agenda's view of calendar 

### ISSUE THREAD

**Issue by SanazDn** [OpenTree-Education/rhizone-lms#471]
## Expected behaviour
 Green colour background for all day activity in the month/week/day/agenda's view

<img width="1254" alt="Screen Shot 2022-12-05 at 2 44 46 PM" src="https://user-images.githubusercontent.com/45150411/205731004-8f65b3c0-b3d1-450e-9cf2-f566e3c116b8.png">
<img width="1254" alt="Screen Shot 2022-12-05 at 2 45 31 PM" src="https://user-images.githubusercontent.com/45150411/205731049-8b62aa96-cf39-4bc4-b645-bbbd8f322ce7.png">
<img width="1254" alt="Screen Shot 2022-12-05 at 2 55 25 PM" src="https://user-images.githubusercontent.com/45150411/205731093-82f3afe5-9611-425b-aa16-11bfd284daf2.png">
<img width="1254" alt="Screen Shot 2022-12-05 at 2 45 03 PM" src="https://user-images.githubusercontent.com/45150411/205731123-db536009-8608-4ff2-a7ef-14e0d3e10a62.png">

## Actual behaviour
All activities have same colour in month/week/day/agenda's views of calendar 

<img width="1254" alt="Screen Shot 2022-12-05 at 2 57 25 PM" src="https://user-images.githubusercontent.com/45150411/205731377-eee42da6-647e-44d9-b0d6-e17e8f4d9696.png">
<img width="1254" alt="Screen Shot 2022-12-05 at 2 57 33 PM" src="https://user-images.githubusercontent.com/45150411/205731406-8d4a869d-d238-4cc6-9a70-107de59d77e7.png">
<img width="1254" alt="Screen Shot 2022-12-05 at 2 57 43 PM" src="https://user-images.githubusercontent.com/45150411/205731433-38a49e05-7446-4629-87f6-f9c6711da9ea.png">

## Steps to reproduce
_ Define "eventPropGette" as a prop for calendar
_ Set specific colour for all day activities 

## Details and resources
Here is a link for documentation of "eventPropGette"
https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--event-prop-getter 

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by wendyyng** [comment]
Personally I prefer using a different colour for all day events.

To avoid the green background for agenda view, I think you can add `currentView !== 'agenda'`

One thing I noticed and @seidior mentioned in my issue is that the all day activity is a little bit wider than the other activities:
![image](https://user-images.githubusercontent.com/71687298/205747859-2f966208-f36a-44f8-b26e-403895514de3.png)

**Comment by daveytech** [comment]
Great work and thank you for the screenshots. The group voted for a colour change but a darker blue. Could you present us with two different options to choose from in a darker blue and share on screenshots?

**Comment by SanazDn** [comment]
Could you please vote which colour is a better match:
1.
<img width="1254" alt="Screen Shot 2022-12-06 at 3 53 57 PM" src="https://user-images.githubusercontent.com/45150411/206021691-9115c1fe-6f78-4f14-8446-34501444904c.png">

2.
<img width="1254" alt="Screen Shot 2022-12-06 at 3 53 30 PM" src="https://user-images.githubusercontent.com/45150411/206021772-897a1062-37eb-46aa-b305-df4d62c7911c.png">
 
3.
<img width="1254" alt="Screen Shot 2022-12-06 at 3 51 31 PM" src="https://user-images.githubusercontent.com/45150411/206021867-dc1770f2-8927-4387-b77a-c3cba3d5b614.png">

4.
<img width="1254" alt="Screen Shot 2022-12-06 at 3 51 00 PM" src="https://user-images.githubusercontent.com/45150411/206021966-24fe1cf4-32b7-439f-8853-b0015d705942.png">

**Comment by wendyyng** [comment]
I think I like the first option the most!

**Comment by rrabinovitch** [comment]
I also vote for the first or second ones (they look quite similar to me)

**Comment by SanazDn** [comment]
I updated the code and also changed the height for all day activity in the week/day's view of calendar. 
<img width="1254" alt="Screen Shot 2022-12-07 at 8 34 50 PM" src="https://user-images.githubusercontent.com/45150411/206334806-4940879e-ef32-4338-9c0f-962de92ff456.png">

<img width="1254" alt="Screen Shot 2022-12-07 at 8 35 02 PM" src="https://user-images.githubusercontent.com/45150411/206334835-2a2536d5-6ace-43c6-ac5b-86f7874a8403.png">

**Comment by SanazDn** [comment]
All day activities are wider than other activities but which one do you think is more standard?
<img width="1254" alt="Screen Shot 2022-12-07 at 10 48 28 PM" src="https://user-images.githubusercontent.com/45150411/206352104-ae417efe-3741-4a13-ac47-d18bfc603a42.png">
