### ISSUE TITLE
Database migration needs to be created for seed data for type tables and samples of each assessment type

### ISSUE THREAD

**Issue by seidior** [OpenTree-Education/rhizone-lms#505]
### Describe the Feature / Enhancement

A new migration file needs to be created that has sample data for each type table (`question_types`, `program_participant_roles`, `assessment_submission_states`) as well as sample data for each assessment type (at least one assignment, at least one quiz, and at least one test).

### Additional Details and Resources

ERD: https://drawsql.app/teams/opentree-education/diagrams/assessments

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.

**Comment by seidior** [comment]
(This should be migration file number 22)

**Comment by seidior** [comment]
(Late) EOD Update: I have assigned this group with an intermediate task to create a document of seed data before creating the migration file, since it's a lot easier to craft the syntax once we figure out what needs to be inserted. Once we review the text file / Google Doc with the sample seed data together tomorrow and it is approved, the team will craft the appropriate syntax for inserting the data into the database using the ERD as guide for data types.

Next steps:
- [x] Create a branch to contain code changes
- [x] Create the shared document and craft example seed data for each assessment type as well as the type tables.
- [x] Review the sample data document with @seidior and modify as is necessary.
- [x] Create the migration file (`V022__insert_sample_assessment_data.sql`) and commit it
- [x] Fill in the migration file with the appropriate insert statements and commit those
- [x] If and only if the team working on #504 merges their work into `features/assessments`, incorporate those changes into this branch and test to verify SQL is working

Out of scope:
- `CREATE TABLE`, `ALTER TABLE` SQL commands
- Any changes to the `api` and `webapp` folders

**Comment by Awatanka** [comment]
EOD Update: 
- created the shared document and crafted example seed data for each assessment type as well as the type tables;
- reviewed the sample data document with @seidior and made the necessary modifications;
- created the migration file (V022__insert_sample_assessment_data.sql) and committed it;
- started adding sample data in the migration file;

Next steps:

- [x] continue filling in the migration file with the appropriate insert statements and commit those
- [x] If the team working on https://github.com/OpenTree-Education/rhizone-lms/issues/504 merges their work into features/assessments, incorporate those changes into this branch and test to verify SQL is working

**Comment by Awatanka** [comment]
EOD Update:
- added insert statements and seeds for assessment, quiz, and test into migration file V022__insert_sample_assessment_data.sql
- formated file V022__insert_sample_assessment_data.sql

Next step:
- [x]  incorporate changes from 504 into our branch and test to verify SQL is working

**Comment by seidior** [comment]
I took the opportunity to review your code before you've created a pull request, hopefully saving a few days of general branch administration and back-and-forth communication. For the most part, it's pretty close to the document that we worked on containing sample data to insert into the database for our feature. Great work translating this over to SQL as well as crafting the questions and answers!

I merged in the changes from the teams working on #504 and #506 into my local `505-database-migration-tables-samples` branch so that I could check your SQL syntax and identify opportunities to improve the code in the migration file. The upside of doing this is that I can see a few steps ahead and jump in front of issues before they arise; the downside is that all of my changes to your migration file collapsed into one commit, since the process I used to merge in those branches isn't trivially compatible with having atomic commits.

So, since I did... basically one giant commit, let me share what changes I made along the way:

- I reformatted the migration file, adding more consistent spacing, indentation, and quote types; removing the comments; and adding an empty line at the end of the file that was missing. (You should always have an empty line at the end of your source files.)
- I fixed my faulty `activity_types` insert syntax I wrote for you to actually work properly.
- I added values for the `assessment_submission_states` and `program_participant_roles` tables.
- I renamed the example quiz and the example test and changed their dates so they can be more useful during development.
- I changed the "multiple choice" question type to "single choice" to better differentiate it from a future potential question type where you are able to select multiple answers.
- I corrected the example program assessment with valid data and added the two missing program assessments.
- I fixed grammar and other mistakes in the questions, including an error where question 3 in the quiz onward (including all questions in the test) it seemed that the correct answer row ID was off by 3.
- I fixed any straightforward problems in the answers that I could see, including switching the answer for the React JSX component to use paragraph tags instead of heading tags since the question specified "text".
- The final `INSERT` statement ended in a comma, not a semicolon. This was fixed.

As it stands now, the syntax is valid and you're ready for a pull request. However, I would recommend reviewing my changes and making any changes of your own if you do not agree with my changes or if you feel I've made any mistakes.

Once you've done that, open a PR to merge the commits from your branch into `features/assessments`, fill out the PR appropriately, submit it, and let the cohort channel know you've opened a PR so they can review it.
