### ISSUE TITLE
API routes need to be added for each supported assessment feature

### ISSUE THREAD

**Issue by seidior** [OpenTree-Education/rhizone-lms#506]
### Describe the Feature / Enhancement

Each assessment feature will need an API route to be able to update the database. In this first step, we need to add routes for each assessment feature.

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.

**Comment by seidior** [comment]
EOD Update: I have assigned this group with an intermediate task to create a list of routes that they need before creating the router files. Once we review the text file / Google Doc with the list of routes (and associated HTTP verbs) together tomorrow and they are approved, the team will create the associated router files, wire them up into `server.ts`, and have each respond to the corresponding routes with a basic message of their choosing and an appropriate HTTP status.

Next steps:
- [ ] Create shared Google Doc /  text file that lists out every route needed within `api` to support every feature we're building out as well as the associated HTTP verb for that route. (Bonus points: the expected possible HTTP status codes for each of these routes.) This list will encompass all the routes for both the *mentor*/*facilitator* and the *mentee*/*participant*. (The same route may have different behavior depending on who's logged in.)
- [ ] Review the routes with @seidior for approval and modify as is necessary.
- [ ] Create a branch to contain code changes.
- [ ] Create the route files, add them to `server.ts`, and respond to each route with a placeholder message and HTTP status.

Out of scope:
- Any internal functionality for the routes, including anything database related (This will be started on next week.) or anything related to `principalId`.
- Service files
- Database migrations
- Webapp routing
- Unit tests for the routes

**Comment by kaiyolau** [comment]
we have made routes for the assessment router and added one more route to the program router.
