### ISSUE TITLE
API service file needs to be created for the assessments feature and wired up to the router file

### ISSUE THREAD

**Issue by seidior** [OpenTree-Education/rhizone-lms#515]
### Describe the Feature / Enhancement

The `assessmentsRouter.ts` file needs to talk to the database to retrieve the correct information for each request. To do this, it will need to call functions in a new `assessmentsService.ts` file that retrieves or submits the correct information into and from the database.

This file will need to have functions defined, function header comments, and a test file.

### Additional Details and Resources

You can reference the routes defined in pull request #509.

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.

**Comment by Paryssatis** [comment]
EOD update: We have written out some of the pseudocode for the assessmentService.ts file. We learned from Mays how to use Postman to test out routes. Now we will try to finish one more function each before tomorrow in assessmentService.ts.

**Comment by Paryssatis** [comment]
EOD update: We wrote the preliminary deleteAssessmentById and putAssessmentId functions as well as their corresponding routes. Tomorrow we will continue our work with the functions that are left to write.

**Comment by Paryssatis** [comment]
EOD update: Added/worked on update/PUT request in both service and router file for assessments. Tomorrow we will continue working on the service methods/routes for each request needed.

**Comment by Awatanka** [comment]
EOD update: We added models according to issue #517 and worked on the service function responsible for the PUT /assessment route. 
Next week, we will continue adding and improving routes for the endpoints. The following steps are on our agenda:
- [ ] Import the necessary functions from assessmentsService.ts for the remaining routes.
- [ ]  Define routes in assessmentsRouter.ts for the following endpoints:
 /submission/:submissionId
 /assessments/:assessmentId/submission/:submissionId
 /assessments/:assessmentId/submission/new
- [ ]  Use the imported functions from assessmentsService.ts to handle the logic for each route.
- [ ]  Write tests to ensure the functionality of the new routes.

**Comment by seidior** [comment]
Hi team! I had the opportunity to review your code over the weekend. I think you have a great start here. There are a couple of things I'd like you to consider going into this week:

- There shouldn't be a one-to-one relationship between the routes and the functions in the service file. Don't worry if the number of model functions don't match up with the number of routes.
- I'd encourage you to think more systematically about what is happening for each of the routes in order to figure out what model functions you will need. Let me give you an example that helps illustrate this:

`[GET] /assessments/:assessmentId` - Program participants should be able to get information about the assessment, including a list of their submissions; program facilitators should be able to get information about the assessment, including a list of all submissions to this assessment for all program participants.

1. Validate that the assessment ID exists in the `program_assessments` table. Get the program ID.
2. Check to see if the principal ID is enrolled / facilitating the program.
  - If the principal ID is a participant, retrieve info about the curriculum and program assessments as well as a list of their submissions (without responses).
  - If the principal ID is a facilitator, retrieve info about the curriculum and program assessments (including questions and answers) as well as information about all participant submissions for this program assessment (but not their responses).
  - If the principal ID is not a part of this program, return an error.
3. Return the appropriate information to the client.

This means we'd need the following functions:
- a function to return the curriculum assessment ID and program ID given a program assessment ID.
- a function to return the role of the participant in a given program
- a function to return details about the curriculum assessment given a curriculum assessment ID, with an optional flag to determine whether or not questions and answers should be included in the return value.
- a function to return details about a program assessment given a program assessment ID
- a function to return details about your own submissions or all participants' submissions, with an optional flag to determine whether or not responses should be included in the return value.

Once you've figured that out for every route, then you can converge your answers together to figure out what functions you will need to write and which need to be called from each route. Along the way, figure out how you can test each route and model function adequately to ensure they are working properly.

**Comment by behrooz-a** [comment]
EOD update: we worked on various functions:
- a function to return the curriculum assessment ID and program ID given a program assessment ID
- a function to return the role of the participant in a given program
- a function to return details about the curriculum assessment given a curriculum assessment ID, with an optional flag to determine whether or not questions and answers should be included in the return value.
- a function to return details about a program assessment given a program assessment ID

Tomorrow, we will continue working on the following functions.  Also, we need to spend time on program service and program routes to find out how they can help us define those functions.

**Comment by Awatanka** [comment]
EOD update: we were working on improvement functions that would be the foundation of our routes. 
Plan for tomorrow: 

- [x] write a function to return details about your own submissions or all participants' submissions, with an optional flag to determine whether or not responses should be included in the return value.
- [x] rewrite, improve and test routes for [GET] /assessments/:assessmentId and [GET] /assessments

**Comment by behrooz-a** [comment]
EOD update: we were working on the following functions and will continue to finish them tomorrow. Also, we will work on defining a route in assessmentsRouter.ts for endpoints: /assessments/:assessmentId/submission/new

 write a function to return details about your own submissions or all participants' submissions, with an optional flag to determine whether or not responses should be included in the return value.
 rewrite, improve and test routes for [GET] /assessments/:assessmentId and [GET] /assessments

**Comment by Awatanka** [comment]
EOD update: Today, we completed work on the get/assessment router and made significant progress in implementing the logic for the get/assessments/:assessmentId/submission/:submissionId endpoint. This endpoint will enable users to retrieve a specific submission for a given assessment. 

Tomorrow, our goals are as follows:
- [ ] Test the response of the get/assessment router to ensure it's working correctly.
- [ ]  Finish implementing the logic for the get/assessments/:assessmentId/submission/:submissionId endpoint.
- [ ] Check the response for get/assessments/:assessmentId
- [ ]  Format the headers for the functions and add descriptions to explain the logic and functionality of each endpoint.

**Comment by seidior** [comment]
EOD Update:

Quite a number of things have changed with this ticket based on our discussions today, and I will update the ticket and all supporting tickets tomorrow with the updated information, from new routes to new service file functions to many other updates.

**Comment by seidior** [comment]
I've fixed the following outstanding issues that arose or were made apparent when bringing together the code on Thursday and Friday:

- The Assessments List Page component, the Assessments Submissions List Page component, and the Assessment Detail Page component were not well tied together and did not link to one another.
- The Assessments List Page component did not properly handle the 'Opened' and 'In Progress' states.
- The Assessments List Page button component was unaware of the user's program status.
- Getting an assessment submission had ambiguous columns in the SQL query.
- The Assessments List Page did not properly handle a lack of assessments being available.
- Dates and times in the TypeScript have switched to Luxon's `DateTime` class instead of native JavaScript Dates.
- Available After and Due Date are now shown on the Assessments Submissions List Page component.
- The Assessments List Page action buttons will jump straight to the new-submission Assessment Detail Page if no submissions by a participant.
- The "New Submission" button on the Assessment Detail Page now more reliably shows based on user's role in program.
- A new "Last Modified" type member has been added to the AssessmentSubmission type to better handle updates of the Assessment Detail Page during auto save.
- useApiData has been extended to support HTTP requests besides just GET requests, without breaking existing behavior.
- Errant duplicate entry in the navbar for "Alternative Assessments" has been removed.
- Assessments Detail Page component now properly orders questions and answer-bubble indicators starting at 1.
- Assessments Detail Page smoothly handles transition from "new" to existing assessment submission display using `useNavigate` from `react-router-dom`.
- Errant deletion of the function definition for createProgramAssessment during merge conflict resolution was reversed.
- Assessment Metadata Bar component has had some minor visual tweaks.
- Example program assessment dates were adjusted to continue the work on our feature.
- Deleting an assessment submission from the database deletes its responses.
- Resuming an in-progress submission has had some intermittent errors squashed.
- Automatic expiration of a submission has had some errors squashed.
- Example data for unit tests is mostly regularized: "matching" for database rows, "example" for structured objects, "sent" for data received from users, "new"/"updated" for new/updated database rows as a result of data receipt action

These are the outstanding issues that need to be addressed:

Priority:
- Functions incomplete in assessmentsRouter or assessmentsService need to be completed.
- assessmentsService functions that are too long or share too much functionality need to be refactored for simplicity.
- 100% code coverage with unit tests in `api` backend.

Stretch:
- Auto state updates (without a change to a response) mechanism was removed from the AssessmentDetailPage because of race conditions. This should be restored in a non-aggressive-to-server way.
- There should be a mechanism for enrolling in a program for demonstration's sake, safely and securely.
- Additional assessments should be created to have assessments in all four tabs on the list page, and dates should be adjusted so these lists stay static for the next year at least.
- Time remaining icon background on assessments detail page should change colour from blue to red with one minute remaining, and the option to disable the time remaining display should be removed.
- A backend call is initiated for every typed letter in an input field on the assessments detail page. This should be minimized to only handle when the field loses focus.
- Consider switching to Luxon's human readable Duration time remaining on assessments detail page instead of our own, if it's better.
- Program completion route
- Mark activities completed for participant after their first assessment is submitted.

Final steps:
- The example data for the backend tests needs to be taken out of its file and incorporated into the test files.
- AssessmentsDummy needs to be deleted.
- Packages need to be updated one last time and the application needs full testing in Docker to ensure the updated packages haven't broken anything.
