### ISSUE TITLE
Helper service file and route need to be added to facilitate development of assessments feature

### ISSUE THREAD

**Issue by seidior** [OpenTree-Education/rhizone-lms#516]
### Describe the Feature / Enhancement

We need to insert dummy data into the database for the tables `program_participants`, `assessment_submissions`, and `assessment_responses`. Please create a route and a service file to handle submitting dummy data for the first assessment, "Assignment 1", for principal ID #3.

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.

**Comment by seidior** [comment]
You will also need to create tests for these files, and you should also have these routes:
- one that assigns a principalId to be a participant in a program ("Spring 2023")
- one that changes the principalId to be a facilitator for that program

**Comment by seidior** [comment]
These routes should be created:

<table>
<thead>
<tr>
<th>HTTP Verb</th>
<th>Route</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>GET</td>
<td>/assessmentsDummy/makeParticipant/:programId/:participantId</td>
<td>This adds a principalId to a program in the role of participant</td>
</tr>
<tr>
<td>GET</td>
<td>/assessmentsDummy/submitAssessment/:participantId</td>
<td>This triggers adding the submission for assignment 1 for that participant ID into the <code>assessment_submissions</code> and <code>assessment_responses</code> tables</td>
</tr>
<tr>
<td>GET</td>
<td>/assessmentsDummy/makeFacilitator/:programId/:participantId</td>
<td>This adds/switches a principalId for a program to the role of facilitator</td>
</tr>
<tr>
<td>GET</td>
<td>/assessmentsDummy/startAssessment/:assessmentId/:participantId</td>
<td>This creates a new submission for the test, which is timed, so we can test the timer feature.</td>
</tr>
</tbody>
</table>

**Comment by abdalbagi93** [comment]
#516 EOD update: we created a middleware and service. 
We need to create and insert dummy data into the database for the tables program_participants, and assessment_submissions.
tomorrow we will create routes and functions.

**Comment by mays4** [comment]
#516 EOD Summary : Today I worked in routers and services.
 Tasks that remain before your issue is complete: there is one route need to be created and in the service file there are queries need to complete 
Tomorrow: continue to work on routes and services  and fix bugs.

**Comment by mays4** [comment]
516 EOD Summary : Today I worked in the last route and added two files for testing 
Tasks that remain before your issue is complete: adding more test and fixing bugs 
Tomorrow: continue to work  on testing and fixing bugs.

**Comment by seidior** [comment]
Hi team! I had an opportunity to review your code over the weekend. You've got a good start so far, and I have no notes that I haven't otherwise shared with you along the way. Keep at it; you're getting quite close to finishing out this ticket.

**Comment by mays4** [comment]
EOD added update response in service file , and worked on testing
Tasks that remain before your issue is complete:fixing bugs in testing
