### ISSUE TITLE
Expected format for each route of assessments feature (input + output) should be defined

### ISSUE THREAD

**Issue by seidior** [OpenTree-Education/rhizone-lms#517]
### Describe the Feature / Enhancement

For each route defined in the list of routes that was in #506, the information being sent to the backend and retrieved from the backend needs to be defined in a structure so that we can wire up the backend to the frontend.

These data types will get added to the `api/src/models.d.ts` and `webapp/src/types/api.d.ts` files. However, the structure of these needs to be defined *first* before modifying these files.

### Additional Details and Resources

See here for reference of the routes: https://github.com/OpenTree-Education/rhizone-lms/pull/509

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.

**Comment by mgasquez** [comment]
EOD Update: Today our Team defined the structure for each route in the list #506 api routes of assessmentsRouter.ts.

Overview
It is necessary to review if the structure is complete and type are corrects.
Add to the api/src/models.d.ts and webapp/src/types/api.d.ts files.
 
Tomorrow, we will check if the database's structure is consistent with the structure we defined today.

**Comment by kaiyolau** [comment]
EOD update: Today, our team corrected the request and response data and added the corresponding required data based on the 'Leadership and Team Integration.pdf' document for each route in the #506 API routes list of 'assessmentsRouter.ts'.

Tomorrow, we will continue updating the remaining data that we didn't finish today.

**Comment by behrooz-a** [comment]
EOD update: Today, we spend time on the request and response data and finalized the corresponding required data based on the 'Leadership and Team Integration.pdf' and product specification documents for each route in the #506  API routes. 

Tomorrow, we will start coding and getting the data from the database and send it back to the clients (users).

**Comment by mgasquez** [comment]
EOD Update: We updated and checked the document again following Spencer's suggestions. We shared to team Birch what we already have done.

Tomorrow It is necessary to do a final review to check if the structure is complete then add the data types to the api/src/models.d.ts and webapp/src/types/api.d.ts files.

**Comment by kaiyolau** [comment]
EOD Update: We finished the document again following Spencer's suggestions. it's a lot of intelligent work as Spencer mentioned, so forget about what we've done this week and enjoy your weekend, have a fresh mind for next week!

**Comment by seidior** [comment]
Hi team! I'm looking forward to seeing how you transform the work from the Google Doc into each of the data types we need. I'll be around to help guide you through this process.

**Comment by mgasquez** [comment]
EOD Update:  Data types added at api/src/models.d.ts.

Overview
It needs a review tomorrow.

**Comment by Paryssatis** [comment]
EOD Update: Finished adding data types to api and models files

Overview
Need to do Pull Request

**Comment by Paryssatis** [comment]
EOD Update: We submitted our pull request and changed necessary changes. After receiving reviews we pushed to the features branch. 

Tomorrow we will begin working on a new issue.
