### ISSUE TITLE
Assessments list page should be broken into components, and its dummy data needs to be reformatted to fit to new route format

### ISSUE THREAD

**Issue by seidior** [OpenTree-Education/rhizone-lms#520]
### Describe the Feature / Enhancement

The assessments list page (`AssessmentsPage.tsx`) should be broken down into components to better fit the pattern laid out in `ProgramsPage`:
- The `AssessmentsListTabs` component should include the markup and functionality for displaying and switching between tabs.
- The `AssessmentsListTable` component should include the markup for displaying the table, selectively showing/hiding headers based on the current tab being selected.

`AssessmentsListTable` should be a child of MUI `TabPanel`s, and `AssessmentsListTabs` should be a child of an MUI `Box`. Both the `TabPanel`s and `Box` should be children of `AssessmentsListPage`.

Next, as part of issue #507, dummy data was created to show an example of a list of assessments. However, after issue #517 is completed, the dummy data needs to be updated to better match the expected protocol for this feature. If any template code needs to be changed to fit the new format, that also will need to be fixed.

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.

**Comment by mgasquez** [comment]
EOD update: Dummy data is reformatted in dataAssessment.ts 

Overview
It was create a new dataAssessment.ts file with dummy data similar to the data in the database.  We still need to make the last review and do some questions. Tomorrow we continue with this part and broken down components.

**Comment by mgasquez** [comment]
EOD update: It is necessary to add type of assessment and check error  when it has 2 interfaces with pipe AssessmentSubmissionsSummary | FacilitatorAssessmentSubmissionsSummary;
