### ISSUE TITLE
Assessment submissions list on frontend needs to be wired up to the backend

### ISSUE THREAD

**Issue by seidior** [OpenTree-Education/rhizone-lms#575]
### Describe the Feature / Enhancement

Now that we have a working route for the assessment submissions list in the API, we should wire up the frontend component to be able to access this route and load the appropriate data.

### Additional Details and Resources

The route should be:

http://api.rhi.zone-development/assessments/program/:programAssessmentId/submissions

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.

**Comment by kaiyolau** [comment]
EOD : 

Successfully retrieve the list of submissions data from the API.
